changelog:
  exclude:
    labels:
      - 'for-release'
      - 'ignore-in-release'
  categories:
    - title: '⚠️ 不兼容变更'
      labels:
        - '不兼容'
    - title: '🔧 修复'
      labels:
        - 'bug'
    - title: '🎉 新特性'
      labels:
        - '特性'
    - title: '✨ 优化'
      labels:
        - '优化'
    - title: '👀 其他变更'
      labels:
        - '*'