name: Publish Snapshot
on:
  push:
    branches:
      - main
      - dev-snapshot**
      - v*.*.*.**
    paths:
      - '**src/main/kotlin/**.kt'
      - '**.kts'
      - '**src/main/java/**.java'

jobs:
  publish-snapshot:
    name: Publish Snapshot
    runs-on: ubuntu-latest
    steps:
      # 检出仓库代码
      - name: Check Out Repo
        uses: actions/checkout@v2

      # setup Java
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8

      # the gpg
      - name: Decode Gpg File
        run: |
          echo "${{ secrets.GPG_B64 }}" > ForteScarlet.gpg.b64
          base64 -d ForteScarlet.gpg.b64 > ForteScarlet.gpg

      # create properties
      - name: Create gradle.properties
        run: |
          echo "org.gradle.parallel=true" > gradle.properties
          echo "org.gradle.workers.max=16" >> gradle.properties
          echo "org.gradle.jvmargs=-Xmx8G -Xms4G -XX:MaxMetaspaceSize=1G -Dfile.encoding=UTF-8 -DisSnapshot=true -DsnapshotOnly" >> gradle.properties

      # setup Gradle
      - name: Gradle Publish Snapshot
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: clean build test publishToSonatype closeAndReleaseStagingRepository -DsnapshotOnly -DisSnapshot=true -Psigning.secretKeyRingFile=ForteScarlet.gpg -Psigning.keyId=${{ secrets.SIGN_KEY_ID }} -Psigning.password=${{ secrets.SIGN_PASS }} -Psonatype.username=${{ secrets.OSS_USERNAME }} -Psonatype.password=${{ secrets.OSS_PASSWORD }}

