name: Publish Snapshot
on:
  push:
    branches:
      - main
    paths:
      - '**src/main/kotlin/**.kt'
      - '**src/main/java/**.java'

jobs:
  publish-snapshot:
    name: Publish Snapshot
    runs-on: ubuntu-latest
    steps:
      # 检出仓库代码
      - name: Check Out Repo
        uses: actions/checkout@v2

      # setup Java
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'gradle'

      # the gpg
      - name: Decode Gpg File
        run: |
          echo "${{ secrets.GPG_B64 }}" > ForteScarlet.gpg.b64
          base64 -d ForteScarlet.gpg.b64 > ForteScarlet.gpg

      # setup Gradle
      - name: Gradle Publish Snapshot
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: clean build test publishToSonatype closeAndReleaseStagingRepository -DsnapshotOnly -DisSnapshot=true -Psigning.secretKeyRingFile=ForteScarlet.gpg -Psigning.keyId=${{ secrets.SIGN_KEY_ID }} -Psigning.password=${{ secrets.SIGN_PASS }} -Psonatype.username=${{ secrets.OSS_USERNAME }} -Psonatype.password=${{ secrets.OSS_PASSWORD }} -Porg.gradle.jvmargs="org.gradle.jvmargs=-Xmx4G -Xms4G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UT-8"

