name: Publish Snapshot
on:
  push:
    branches:
      - main
      - dev-snapshot**
      - v*.*.*.**
    paths:
      - '**src/main/kotlin/**.kt'
      - '**.kts'
      - '**src/main/java/**.java'
      - 'buildSrc'

env:
  IS_CI: true
  GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
  GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
  GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  SIMBOT_IS_SNAPSHOT: true
  SIMBOT_SNAPSHOT_ONLY: true
  GRADLE_OPTS: "-Dfile.encoding=UTF-8"

jobs:
  publish-snapshot:
    name: Publish Snapshot
    runs-on: ubuntu-latest
    steps:
      # 检出仓库代码
      - name: Check Out Repo
        uses: actions/checkout@v3

      # setup Java
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Run All Tests
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          arguments: assemble test

      # publish
      - name: Gradle Publish Snapshot
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          arguments: |
            publishToSonatype
            closeAndReleaseStagingRepository
            --info 
            --warning-mode all
            -x test
            --build-cache
            -Porg.gradle.jvmargs="-Xmx4g -Xms4g -XX:MaxMetaspaceSize=2g -Dfile.encoding=UTF-8" 
            -Porg.gradle.daemon=false
